<?
$this->headLink()
    ->prependStylesheet($this->basePath() . '/css/input-multivalue.css')
    ->prependStylesheet($this->basePath() . '/css/manage-orders.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-datatables.css');

$this->headScript()
    ->prependFile($this->basePath() . '/js/jquery-ui-1.8.18.js')
    ->prependFile($this->basePath() . '/js/bootstrap-tab.js')
    ->prependFile($this->basePath() . '/js/data-tables.js')
    ->prependFile($this->basePath() . '/js/manage-orders.js')
    ->prependFile($this->basePath() . '/js/input-multivalue.js');
?>
</div> <? //break out of the container div ?>

<div id="speck-order-layout" class="container-fluid">
    <div class="row-fluid layout-inner-wrap">
        <div id="search" class="span2">
            <?=$this->render('/speck-order/order-management/search/index'); ?>
        </div>
        <div class="content span10">
            <div id="search-button" title="show/hide the search pane"><i class="icon-search"></i></div>
            <?php echo $this->content; ?>
        </div>
    </div>
</div>

<div id="search-hide" class="hide">
</div>

<div> <? //return to the container div ?>
