<?=$this->form()->openTag($form);?>
<div class="row-fluid">
    <div class="span12">
        <?
            $input = $form->get('company')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
</div>
<div class="row-fluid">
    <div class="span4">
        <?
            $input = $form->get('first_name')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
    <div class="span4">
        <?
            $input = $form->get('middle_name')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
    <div class="span4">
        <?
            $input = $form->get('last_name')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
</div>
<div class="row-fluid">
    <?
        $input = $form->get('street_address')->setAttribute('class', 'span12');
        $input->setAttribute('placeholder', $input->getLabel());
    ?>
    <?=$this->formInput($input); ?>
</div>
<div class="row-fluid">
    <?
        $input = $form->get('street_address_2')->setAttribute('class', 'span12');
        $input->setAttribute('placeholder', $input->getLabel());
    ?>
    <?=$this->formInput($input); ?>
</div>
<div class="row-fluid">
    <div class="span3">
        <?
            $input = $form->get('city')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
    <div class="span3">
        <?
            $input = $form->get('province')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
    <div class="span3">
        <?
            $input = $form->get('postal_code')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formInput($input); ?>
    </div>
    <div class="span3">
        <?
            $input = $form->get('country')->setAttribute('class', 'span12');
            $input->setAttribute('placeholder', $input->getLabel());
        ?>
        <?=$this->formSelect($input); ?>
    </div>
</div>
<div class="buttons">
    <input type="button" class="address-cancel btn" value="Cancel"/>
    <input type="submit" class="address-update btn btn-primary" value="Update Address"/>
</div>
<?=$this->form()->closeTag($form);?>
