<tr>
    <td>
        <?//$status = $order->getStatus(); ?>
        <?//=$this->speckOrder()->orderStatusToIcon($status); ?>
        pending
    </td>
    <td>
        <? //$flags = $order->getFlags(); ?>
        <?//=$this->speckOrder()->flagsToIcons($flags); ?>
        AEIOU
    </td>
    <td>
        <a href="/manage-order/123456">
        <?//=$order->getId(); ?>
        S1234556
        </a>
    </td>
    <td>
        <?//=$order->getBilling()->getName(); ?>
        Joe Schmo -
        <?//=$order->getBilling()->getAddress(); ?>
        <i>123 S St Gilbert AZ 85297</i>
    </td>
    <td>
        <?//=$order->getShipping()->getName(); ?>
        Joe Schmo -
        <?//=$order->getShipping()->getAddress(); ?>
        <i>123 S St Gilbert AZ 85297</i>
    </td>
    <td>
        <?//=$order->getPrice(); ?>
        $99.99
    </td>
    <td>
        <?//$method=$order->getPayment()->getPaymentMethod(); ?>
        <?//=$this->speckOrder()->paymentMethodToIcon($method); ?>
        Visa
    </td>
    <td>
        <?//=$order->getCsrName(); ?>
        Tahni G
    </td>
    <td>
        <?//=$order->getCompletedDateTime(); ?>
        Today 12:11 pm
    </td>
</tr>
