<strong>Cart Contents</strong>
<?
    // $items = $order->getLineItems();
    // $options = array(//special view partial??);
?>
<?//=$this->lineItems($items, $options);?>
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="cart-items">
    <thead>
        <tr>
            <th class="item">Item</th>
            <th class="uom-qty">Uom + Qty</th>
            <th class="price">Unit Price</th>
            <th class="line-total">Line Total</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td>Item</td>
            <td>Uom + Qty</td>
            <td>Unit Price</td>
            <td>Line Total</td>
        </tr>
        <tr>
            <td>Item</td>
            <td>Uom + Qty</td>
            <td>Unit Price</td>
            <td>Line Total</td>
        </tr>
        <tr class="odd">
            <td>Item</td>
            <td>Uom + Qty</td>
            <td>Unit Price</td>
            <td>Line Total</td>
        </tr>
        <tr>
            <td>Item</td>
            <td>Uom + Qty</td>
            <td>Unit Price</td>
            <td>Line Total</td>
        </tr>
    </tbody>
</table>
