<?
    //$orderId = $order->getOrderId();
    $orderId = 12345;
    //$orderNumber = $order->getOrderNumber();
    $orderNumber = 's12345';
?>

<div class="span9">
    <p><strong>Order Number:</strong> <?=$orderNumber;?></p>
    <p><strong>Customer:</strong> <a href="/admin/manage-customer/12345"><? echo 'johnsmith@domain.tld'; ?></a></p>
    <div class="row-fluid">
        <div class="span6 address-block bill well" data-address_type="billing" data-order_id="<?=$orderId;?>">
            <div class="row-fluid title">
                Bill To:
                <i class="icon-pencil edit-button" title="edit"></i>
            </div>
            <div class="address">
                <?//=$this->render('/speck-order/order-management/order/address-block'); ?>
            </div>
            <div class="edit hide">
            </div>
        </div>
        <div class="span6 address-block bill well" data-address_type="shipping" data-order_id="<?=$orderId;?>">
            <div class="row-fluid title">
                Ship To:
                <i class="icon-pencil edit-button" title="edit"></i>
            </div>
            <div class="address">
                <?//=$this->render('/speck-order/order-management/order/address-block'); ?>
            </div>
            <div class="edit hide">
            </div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="order-actions">
            <div class="title">Actions / Reports</div>
        <?= $this->navigation($this->actions)->menu(); ?>
        </div>
    </div>
</div>
<div class="span3"><? //tags-flags ?>
    <div class="row-fluid">
        <div class="span6">
            <strong>Flags</strong>
            <?// foreach ($order->getFlags() as $flag) : ?>
            <? foreach(array('asdf', 'foo', 'bar') as $flag) : ?>
                <p><?=$flag;?></p>
            <? endforeach; ?>
        </div>
        <div class="span6">
            <strong>Tags</strong>
            <?= $this->speckOrder()->orderTagsForm(null, array(4=>4), true); ?>
        </div>
    </div>
</div>
