<h3>John Smith</h3>
<strong>Orders</strong>
<table id="customer-orders" cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th class="order-number">Order Number</th>
            <th class="order-date">Date</th>
            <th class="ship-to">Ship To</th>
            <th class="bill-to">Bill To</th>
            <th class="cart-total">Cart Total</th>
        </tr>
    </thead>
    <tbody>
        <tr class="odd">
            <td><a href="/manage-order/12345">s12345</a></td>
            <td>10/21/12</td>
            <td>123 s st E Gilbert AZ 12345</td>
            <td>123 s st E Gilbert AZ 12345</td>
            <td>$121.19</td>
        </tr>
        <tr>
            <td><a href="/manage-order/12345">s12345</a></td>
            <td>10/21/12</td>
            <td>123 s st E Gilbert AZ 12345</td>
            <td>123 s st E Gilbert AZ 12345</td>
            <td>$1829.97</td>
        </tr>
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function(){
        toggleSearch();
        $('#search a[href="#search-customer"]').tab('show');
    });
</script>
