</div> <? //break out of the container div ?>

<div class="container-fluid">
    <div id="order-management" class="row-fluid">

        <div class="span3" id="order-search-panes">
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#search-order">Orders</a></li>
                <li><a data-toggle="tab" href="#search-customer">Customers</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane search-pane" id="search-customer">
                    Search Customers
                </div>
                <div class="active tab-pane search-pane" id="search-order">
                    <?=$this->speckOrder()->orderSearchForm(true, array('attributes' => array('id' => 'order-search'))); ?>
                </div>
            </div>
        </div>
        <div class="span9">
            <ul class="nav nav-tabs" id="order-manager-tabs">
                <li class="active"><a data-toggle="tab" href="#order-pane">Orders</a></li>
            </ul>
            <div id="order-manager-tab-containers" class="tab-content row-fluid">

                <div class="tab-pane active span12" id="order-pane">
                    <table class="table table-striped table-bordered" id="orders">
                        <thead>
                            <tr>
                                <th class="status">Status</th>
                                <th class="flags">Flags</th>
                                <th class="order_num">Order #</th>
                                <th class="billto">Bill To</th>
                                <th class="shipto">Ship To</th>
                                <th class="total">Total</th>
                                <th class="payment">Payment</th>
                                <th class="csr">Assigned To</th>
                                <th class="date_time">Date / Time</th>
                            </tr>
                        </thead>
                        <tbody>
                            <? foreach ($orders as $order) : ?>
                                <?=$this->render('/speck-order/order-management/order/row'); ?>
                            <? endforeach; ?>
                        </tbody>
                    </table>
                </div>

            </div>
        </div>

    </div>
</div>

<div> <? //return to the container div ?>
