<div class="order_header">
    <?=$this->placeHolders['header'];?>
</div>
<div class="row-fluid">
    <div class="span8 order_1">
        <?=$this->placeHolders['content_1'];?>
    </div>
    <div class="span4 order_2">
        <?=$this->placeHolders['content_2'];?>
    </div>
</div>
<div class="row-fluid order_3">
    <?=$this->placeHolders['content_3'];?>
</div>
<div class="order_footer">
    <?=$this->placeHolders['footer'];?>
</div>
